services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres # Volume anônimo (não será persistido)
      - ./src/main/resources/db/migration/update-schema.sql:/docker-entrypoint-initdb.d/update-schema.sql # creates aqui
      - ./postgres-data/data/data.sql:/docker-entrypoint-initdb.d/data.sql # inserts aqui

  spring:
    container_name: api-codando
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-app:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_APPLICATION_NAME: api-codando
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties

