networks:
  codando-net:
    driver: bridge

services:
  spring1:
    container_name: api-codando1
    image: ismaelog1/codando_api:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.0.165:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - codando-net

  spring2:
    container_name: api-codando2
    image: ismaelog1/codando_api:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.0.165:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - codando-net

volumes:
  postgres-data: