version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./path/to/your/default.conf:/etc/nginx/conf.d/default.conf  # Aponte para seu arquivo de configuração
    networks:
      - minha-rede  # Conectando à rede criada

networks:
  codando-rede:
    external: true  # Usando uma rede externa
