CREATE TABLE aluno
(
    id_aluno        INT NOT NULL,
    nome            VARCHAR(255),
    sobrenome       VARCHAR(255),
    apelido         VARCHAR(255),
    senha           VARCHAR(255),
    status          VARCHAR(255),
    moedas          INT,
    id_turma        INT,
    id_escolaridade INT,
    CONSTRAINT pk_aluno PRIMARY KEY (id_aluno)
);

CREATE TABLE aula
(
    id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo            VARCHAR(255)                         NOT NULL,
    descricao         VARCHAR(255)                         NOT NULL,
    nivel_dificuldade INT,
    pontuacao_maxima  INT,
    id_tema           INT,
    CONSTRAINT pk_aula PRIMARY KEY (id)
);

CREATE TABLE csv
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ano_letivo          INT,
    nm_diretoria        VARCHAR(23),
    nm_municipio        VARCHAR(26),
    cd_rede_ensino      BOOLEAN                              NOT NULL,
    cd_escola           INT                                  NOT NULL,
    nm_completo_escola  VARCHAR(80),
    cd_tp_identificador INT                                  NOT NULL,
    apr1                DOUBLE PRECISION                     NOT NULL,
    rep1                DOUBLE PRECISION                     NOT NULL,
    aba1                DOUBLE PRECISION                     NOT NULL,
    apr2                DOUBLE PRECISION                     NOT NULL,
    rep2                DOUBLE PRECISION                     NOT NULL,
    aba2                DOUBLE PRECISION                     NOT NULL,
    apr3                DOUBLE PRECISION                     NOT NULL,
    rep3                DOUBLE PRECISION                     NOT NULL,
    aba3                DOUBLE PRECISION                     NOT NULL,
    CONSTRAINT pk_csv PRIMARY KEY (id)
);

CREATE TABLE educador
(
    id_educador INT NOT NULL,
    nome        VARCHAR(255),
    sobrenome   VARCHAR(255),
    email       VARCHAR(255),
    senha       VARCHAR(255),
    CONSTRAINT pk_educador PRIMARY KEY (id_educador)
);

CREATE TABLE escolaridade
(
    id_escolaridade INT          NOT NULL,
    descricao       VARCHAR(255) NOT NULL,
    CONSTRAINT pk_escolaridade PRIMARY KEY (id_escolaridade)
);

CREATE TABLE grade
(
    id_grade INT NOT NULL,
    id_turma INT,
    id_tema  INT,
    CONSTRAINT pk_grade PRIMARY KEY (id_grade)
);

CREATE TABLE modulo
(
    id_modulo INT NOT NULL,
    nome      VARCHAR(255),
    CONSTRAINT pk_modulo PRIMARY KEY (id_modulo)
);

CREATE TABLE progresso_aluno
(
    id_progresso_aluno INT          NOT NULL,
    pontuacao_aluno    INT,
    status_aula        VARCHAR(255) NOT NULL,
    id_aluno           INT,
    id_aula            INT,
    CONSTRAINT pk_progressoaluno PRIMARY KEY (id_progresso_aluno)
);

CREATE TABLE tema
(
    id_tema   INT          NOT NULL,
    nome      VARCHAR(255) NOT NULL,
    id_modulo INT,
    CONSTRAINT pk_tema PRIMARY KEY (id_tema)
);

CREATE TABLE turma
(
    id_turma        INT          NOT NULL,
    nome            VARCHAR(255) NOT NULL,
    sobrenome       VARCHAR(255) NOT NULL,
    id_escolaridade INT,
    id_educador     INT,
    CONSTRAINT pk_turma PRIMARY KEY (id_turma)
);

ALTER TABLE aluno
    ADD CONSTRAINT uc_aluno_idescolaridade UNIQUE (id_escolaridade);

ALTER TABLE aula
    ADD CONSTRAINT uc_aula_idtema UNIQUE (id_tema);

ALTER TABLE progresso_aluno
    ADD CONSTRAINT uc_progressoaluno_idaluno UNIQUE (id_aluno);

ALTER TABLE progresso_aluno
    ADD CONSTRAINT uc_progressoaluno_idaula UNIQUE (id_aula);

ALTER TABLE aluno
    ADD CONSTRAINT FK_ALUNO_ON_IDESCOLARIDADE FOREIGN KEY (id_escolaridade) REFERENCES escolaridade (id_escolaridade);

ALTER TABLE aluno
    ADD CONSTRAINT FK_ALUNO_ON_IDTURMA FOREIGN KEY (id_turma) REFERENCES turma (id_turma);

ALTER TABLE aula
    ADD CONSTRAINT FK_AULA_ON_IDTEMA FOREIGN KEY (id_tema) REFERENCES tema (id_tema);

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_IDTEMA FOREIGN KEY (id_tema) REFERENCES tema (id_tema);

ALTER TABLE grade
    ADD CONSTRAINT FK_GRADE_ON_IDTURMA FOREIGN KEY (id_turma) REFERENCES turma (id_turma);

ALTER TABLE progresso_aluno
    ADD CONSTRAINT FK_PROGRESSOALUNO_ON_IDALUNO FOREIGN KEY (id_aluno) REFERENCES aluno (id_aluno);

ALTER TABLE progresso_aluno
    ADD CONSTRAINT FK_PROGRESSOALUNO_ON_IDAULA FOREIGN KEY (id_aula) REFERENCES aula (id);

ALTER TABLE tema
    ADD CONSTRAINT FK_TEMA_ON_IDMODULO FOREIGN KEY (id_modulo) REFERENCES modulo (id_modulo);

ALTER TABLE turma
    ADD CONSTRAINT FK_TURMA_ON_IDEDUCADOR FOREIGN KEY (id_educador) REFERENCES educador (id_educador);

ALTER TABLE turma
    ADD CONSTRAINT FK_TURMA_ON_IDESCOLARIDADE FOREIGN KEY (id_escolaridade) REFERENCES escolaridade (id_escolaridade);