
CREATE TABLE aluno
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255),
    sobrenome       VARCHAR(255),
    apelido         VARCHAR(255),
    senha           VARCHAR(255),
    status          BOOLEAN,
    moedas          INTEGER,
    senha_turma     VARCHAR(255),
    id_avatar       INTEGER                                  NOT NULL,
    id_turma        INTEGER,
    id_escolaridade INTEGER,
    CONSTRAINT pk_aluno PRIMARY KEY (id)
);

CREATE TABLE aluno_avatar
(
    aluno_id  INTEGER NOT NULL,
    avatar_id INTEGER NOT NULL
);

CREATE TABLE aluno_resposta
(
    aluno_id    INTEGER NOT NULL,
    resposta_id INTEGER NOT NULL
);

CREATE TABLE aula
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo            VARCHAR(255),
    descricao         VARCHAR(255),
    nivel_dificuldade INTEGER,
    pontuacao_maxima  INTEGER,
    tema_id_tema      INTEGER,
    turma_id_turma    INTEGER,
    CONSTRAINT pk_aula PRIMARY KEY (id)
);

CREATE TABLE avatar
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao VARCHAR(255),
    preco     INTEGER                                  NOT NULL,
    imagemurl VARCHAR(255),
    CONSTRAINT pk_avatar PRIMARY KEY (id)
);

CREATE TABLE csv
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ano_letivo          INTEGER,
    nm_diretoria        VARCHAR(23),
    nm_municipio        VARCHAR(26),
    cd_rede_ensino      BOOLEAN                                  NOT NULL,
    cd_escola           INTEGER                                  NOT NULL,
    nm_completo_escola  VARCHAR(80),
    cd_tp_identificador INTEGER                                  NOT NULL,
    apr1                DOUBLE PRECISION                         NOT NULL,
    rep1                DOUBLE PRECISION                         NOT NULL,
    aba1                DOUBLE PRECISION                         NOT NULL,
    apr2                DOUBLE PRECISION                         NOT NULL,
    rep2                DOUBLE PRECISION                         NOT NULL,
    aba2                DOUBLE PRECISION                         NOT NULL,
    apr3                DOUBLE PRECISION                         NOT NULL,
    rep3                DOUBLE PRECISION                         NOT NULL,
    aba3                DOUBLE PRECISION                         NOT NULL,
    CONSTRAINT pk_csv PRIMARY KEY (id)
);

CREATE TABLE educador
(
    id_educador INTEGER NOT NULL,
    nome        VARCHAR(255),
    sobrenome   VARCHAR(255),
    email       VARCHAR(255),
    senha       VARCHAR(255),
    CONSTRAINT pk_educador PRIMARY KEY (id_educador)
);

CREATE TABLE escolaridade
(
    id_escolaridade INTEGER NOT NULL,
    descricao       VARCHAR(255),
    CONSTRAINT pk_escolaridade PRIMARY KEY (id_escolaridade)
);

CREATE TABLE grade
(
    id_grade INTEGER NOT NULL,
    CONSTRAINT pk_grade PRIMARY KEY (id_grade)
);

CREATE TABLE mensagem
(
    id_mensagem INTEGER NOT NULL,
    texto       VARCHAR(255),
    data_envio  TIMESTAMP WITHOUT TIME ZONE,
    id_turma    INTEGER,
    CONSTRAINT pk_mensagem PRIMARY KEY (id_mensagem)
);

CREATE TABLE modulo
(
    id_modulo      INTEGER NOT NULL,
    nome           VARCHAR(255),
    grade_id_grade INTEGER,
    CONSTRAINT pk_modulo PRIMARY KEY (id_modulo)
);

CREATE TABLE mural
(
    id_mural INTEGER NOT NULL,
    CONSTRAINT pk_mural PRIMARY KEY (id_mural)
);

CREATE TABLE pergunta
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto    VARCHAR(255),
    contador INTEGER,
    aula_id  INTEGER,
    CONSTRAINT pk_pergunta PRIMARY KEY (id)
);

CREATE TABLE progresso_aluno
(
    id_progresso_aluno INTEGER NOT NULL,
    pontuacao_aluno    INTEGER NOT NULL,
    status_aula        VARCHAR(255),
    fk_aluno           INTEGER,
    fk_aula            INTEGER,
    CONSTRAINT pk_progressoaluno PRIMARY KEY (id_progresso_aluno)
);

CREATE TABLE quiz
(
    id_quiz INTEGER NOT NULL,
    texto   VARCHAR(255),
    CONSTRAINT pk_quiz PRIMARY KEY (id_quiz)
);

CREATE TABLE resposta
(
    id_resposta INTEGER NOT NULL,
    texto       VARCHAR(255),
    correta     BOOLEAN,
    pergunta_id INTEGER,
    CONSTRAINT pk_resposta PRIMARY KEY (id_resposta)
);

CREATE TABLE tema
(
    id_tema   INTEGER NOT NULL,
    nome      VARCHAR(255),
    id_modulo INTEGER,
    CONSTRAINT pk_tema PRIMARY KEY (id_tema)
);

CREATE TABLE turma
(
    id_turma        INTEGER      NOT NULL,
    nome            VARCHAR(255) NOT NULL,
    senha           VARCHAR(255) NOT NULL,
    id_escolaridade INTEGER,
    id_educador     INTEGER,
    status_turma    BOOLEAN      NOT NULL,
    CONSTRAINT pk_turma PRIMARY KEY (id_turma)
);

ALTER TABLE aluno
    ADD CONSTRAINT FK_ALUNO_ON_IDESCOLARIDADE FOREIGN KEY (id_escolaridade) REFERENCES escolaridade (id_escolaridade);

ALTER TABLE aluno
    ADD CONSTRAINT FK_ALUNO_ON_IDTURMA FOREIGN KEY (id_turma) REFERENCES turma (id_turma);

ALTER TABLE aula
    ADD CONSTRAINT FK_AULA_ON_TEMA_IDTEMA FOREIGN KEY (tema_id_tema) REFERENCES tema (id_tema);

ALTER TABLE aula
    ADD CONSTRAINT FK_AULA_ON_TURMA_IDTURMA FOREIGN KEY (turma_id_turma) REFERENCES turma (id_turma);

ALTER TABLE mensagem
    ADD CONSTRAINT FK_MENSAGEM_ON_IDTURMA FOREIGN KEY (id_turma) REFERENCES turma (id_turma);

ALTER TABLE modulo
    ADD CONSTRAINT FK_MODULO_ON_GRADE_IDGRADE FOREIGN KEY (grade_id_grade) REFERENCES grade (id_grade);

ALTER TABLE pergunta
    ADD CONSTRAINT FK_PERGUNTA_ON_AULA FOREIGN KEY (aula_id) REFERENCES aula (id);

ALTER TABLE progresso_aluno
    ADD CONSTRAINT FK_PROGRESSOALUNO_ON_FKALUNO FOREIGN KEY (fk_aluno) REFERENCES aluno (id);

ALTER TABLE progresso_aluno
    ADD CONSTRAINT FK_PROGRESSOALUNO_ON_FKAULA FOREIGN KEY (fk_aula) REFERENCES aula (id);

ALTER TABLE resposta
    ADD CONSTRAINT FK_RESPOSTA_ON_PERGUNTA FOREIGN KEY (pergunta_id) REFERENCES pergunta (id);

ALTER TABLE tema
    ADD CONSTRAINT FK_TEMA_ON_IDMODULO FOREIGN KEY (id_modulo) REFERENCES modulo (id_modulo);

ALTER TABLE turma
    ADD CONSTRAINT FK_TURMA_ON_IDEDUCADOR FOREIGN KEY (id_educador) REFERENCES educador (id_educador);

ALTER TABLE turma
    ADD CONSTRAINT FK_TURMA_ON_IDESCOLARIDADE FOREIGN KEY (id_escolaridade) REFERENCES escolaridade (id_escolaridade);

ALTER TABLE aluno_avatar
    ADD CONSTRAINT fk_aluava_on_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id);

ALTER TABLE aluno_avatar
    ADD CONSTRAINT fk_aluava_on_avatar FOREIGN KEY (avatar_id) REFERENCES avatar (id);

ALTER TABLE aluno_resposta
    ADD CONSTRAINT fk_alures_on_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id);

ALTER TABLE aluno_resposta
    ADD CONSTRAINT fk_alures_on_resposta FOREIGN KEY (resposta_id) REFERENCES resposta (id_resposta);